[package]
name = "linkz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
scraper = "0.16.0"
tokio = { version = "1.28.2", features = ["full"] }
url = "2.4.0"
